### ISSUE TITLE
 1.9.4-1.0 crashes dedicated forge server 1.9 build 1907 on startup

### ISSUE THREAD

**Issue by kreezxil** [MattDahEpic/AutoOreDictConvert1.8#1]
Issue: auto ore dictionary converter 1.9.4-1.0 crashes dedicated forge server 1.9 build 1907 on startup

seems it didn't care that you made it compatible with 1.9

crash report:
https://gist.github.com/6fa929ef9b2e05bc4be9880a0f1841c8

fml server latest:
https://gist.github.com/d30f1efc6d226f786d7912995280a584

**Comment by MattDahEpic** [comment]
1.9.4 versions are for 1.9.4 clients, while you are running 1.9.0. I will change the curseforge labels to respect this.
