### ISSUE TITLE
[1.16.3] forge:ores all in the same group now

### ISSUE THREAD

**Issue by YOYOK9** [MattDahEpic/AutoOreDictConvert1.8#11]
It seems that the 1.16 ores have 2 ore dicts. so when I do /odc add while holding an ore it will not only convert the ore of the same type but also all other ores as well. 
Ex: copper ore is forge:ores/copper and forge:ores so it seems to default at forge:ores

Ingots do the same as well. Is there a proper syntax for adding the ores and ingots to add the /ore-ingot option after ther forge:ores?

**Comment by MattDahEpic** [comment]
When you add a conversion with a command it adds conversions for all the tags the item is contained within, for copper it would add `forge:ingots` and `forge:ingots/copper`. I can make it exclude the base level ingots/blocks/ores tags by default but in the short term you can manually remove the forge:ingots entry from the configuration file manually and run /odc reload to have it load from the file again.

**Comment by YOYOK9** [comment]
I will give the config option a shot. Want me to let you know of the outcome? If there is an issue that is.

**Comment by MattDahEpic** [comment]
If there's an issue I'd want to know, yes.

**Comment by YOYOK9** [comment]
So far so good. No issues. Thank you for your help.
