### ISSUE TITLE
Convert From Machine Output ?

### ISSUE THREAD

**Issue by Switch-Back18** [MattDahEpic/AutoOreDictConvert1.8#12]
Can you convert automaticaly an ingot from a Furnace output and not only from a player pick item in his inventory ?

If you can do for all machine output that can be good

Thank's you to read this and considered this ! 

Bye MathisSkate

**Comment by MattDahEpic** [comment]
This mod is primarily meant as a quick way to make sure players only have one type of a specified ore/ingot/block. If you want to change the output of machine recipes I would recommend you use [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker). Some parts of the game you can't change so this mod catches those cases. If you're making a pack I'd recommend using both CraftTweaker and this mod to make sure you don't miss any edge cases. 
For players just playing, you can pipe items into the converter block to convert them without having to have them in your inventory (for AE systems and the like)
