### ISSUE TITLE
"/odc add" makes the held item preferred for every tag that it has.

### ISSUE THREAD

**Issue by ChrisJacobsJr** [MattDahEpic/AutoOreDictConvert1.8#13]
Example: All ingots convert to copper ingots because the copper ingots are preferrred in both forge:ingots/silver and forge:ingots

**to reproduce:** 

hold thermal expansion ingot, type /odc add
pickup ingot

when typing "/odc remove forge:ingot" while holding the ingot the issue resolves and the ingots do not convert outside of what I had intended. 

"/odc add" makes the held item preferred for every tag that it has

**Comment by ChrisJacobsJr** [comment]
did not read the closed issued :(((((

**Comment by nayfaan** [comment]
Actually still an issue, but not with ingots. With mods that adds metal dusts, gears, etc, the mod adds all the tags on the held item to the list. I have a few suggestions:
1. ignore more common base tags (e.g. forge:dusts, forge:gears, forge:coins, forge:plates, etc.)
2. Allow the "/odc add" command to pass arguments of a certain tag like "/odc add forge:dusts/iron"
    i.e.
   -if no argument is passed, adds all tags to conversion
   -if an argument is passed, only add the specified tag to conversion
