### ISSUE TITLE
Feature request: merge items with only its ID's

### ISSUE THREAD

**Issue by Shorepion** [MattDahEpic/AutoOreDictConvert1.8#14]
Merging items separately only by its ID.
example: iceandfire:silver_ore=silentgems:silver_ore (excluding thermalexpansion:silver_ore, so the thermalexpansion silver ore is not being merged)

**Comment by MattDahEpic** [comment]
This'll be in the next version (up momentarily).
To add an item conversion simply add another line to the config with the following format: `modid:item>modid:item` where the input is on the left and output on the right. Tag conversions will work as before (with `=`).
