### ISSUE TITLE
Feature Request: Toggle-able ore converting

### ISSUE THREAD

**Issue by aaaaaaaaaaazzzza** [MattDahEpic/AutoOreDictConvert1.8#15]
Setting up sorting systems to process ore is made difficult by the auto conversion. As it stands, you cannot setup export buses to pull 5 different copper ores from an ME system if they all become the same type of copper ore the second they touch your inventory.

I think it would great if there was a toggleable gui element or command that would enable/disable auto ore conversions.  This would allow the user to disable conversion, take 5 different copper ores, place each one of them into the ME export bus(or other item filters / sorting mods), and then re-enable conversion.

**Comment by MattDahEpic** [comment]
What version are you on? If you are in 1.12 I know there is a ore dictionary export filter that can export every ore of a type from an ME system for conversion by the block. For 1.16 I haven't used AE yet so I'm not sure.

As for the actual feature request, the easiest way would be to temporarily enable the conversion-on-keypress, which will prevent conversions from happening until you press the key. When I have access to a coding computer again I can add a `/odc pause` command which will temporarily disable the conversion for the person who ran it.

**Comment by aaaaaaaaaaazzzza** [comment]
I am on 1.16.

Those sound like great solutions. 

Thank you for such a quick response!
