### ISSUE TITLE
1.16 Items convert only when in inventory

### ISSUE THREAD

**Issue by cobbkris** [MattDahEpic/AutoOreDictConvert1.8#16]
It seems the items only convert when they are in your inventory.  I have used one on 1.12, not sure if it was yours, but when I would mine say a copper ore it would drop the Thermal Series Copper ore automatically.  The version on 1.16 seems to drop the original ore, then when it is in your inventory it is converted to whatever I have set it to convert to (Thermal usually).

I can't remember the issue I had because of this, but I will update this issue if I can remember or encounter something that this would come up.

**Comment by MattDahEpic** [comment]
Even back in 1.12 this mod did not change the drops of ores. If you were in a pack, the maker might have used MineTweaker or another mod to change the drops of ore blocks. In 1.16 they may change the loot tables for the block via a resource pack or using a mod.
