### ISSUE TITLE
Add input to the converter block !

### ISSUE THREAD

**Issue by Switch-Back18** [MattDahEpic/AutoOreDictConvert1.8#18]
Hello !

I think that can be good if we can connect the block to pipe or other things.

You can add gui or other in it like inventory or something (it's an idea)

Because now we can only connect with hopper and it's not good in modded.

Thank you

**Comment by MattDahEpic** [comment]
The converter uses the standard interfaces for item flow, if you can connect your pipes to a chest or a furnace, they will work with the converter. You may need to set the pipes to "push" mode, as the converter does not pull from adjacent slots. It has one slot, only accepts items with a conversion, and takes input on the top and output on the bottom. I won't be adding a GUI as items don't technically stay in the converter, and you should be able to see the inventory with a tooltip mode like The One Probe or WAILA

**Comment by Switch-Back18** [comment]
I'm in 1.16, i tried with pipe from cyclic, mekanism, refined pipes and that not connect together

**Comment by Switch-Back18** [comment]
Did you fix it ? or will you fix it ?

**Comment by MattDahEpic** [comment]
It is now fixed.

**Comment by MattDahEpic** [comment]
Thank you for the issue, I learned a new skill in solving it
