### ISSUE TITLE
Issue converting specific items

### ISSUE THREAD

**Issue by JpegIsMe** [MattDahEpic/AutoOreDictConvert1.8#19]
Hey, I'm having a hard time converting a specific item to another since one item has a certain tag and another doesn't i've seen the example given on your forge page and tried using it, but it doesn't seem to work. 
Any suggestions?
![image](https://user-images.githubusercontent.com/38381978/105616111-62e21180-5da2-11eb-84f3-80369f5447f2.png)

**Comment by MattDahEpic** [comment]
What version of the mod are you using? Does the conversion show up in game via the `/odc list` command?

**Comment by JpegIsMe** [comment]
I'm using the latest version. Here's the image of the /odc list:
![image](https://user-images.githubusercontent.com/38381978/105616580-1ac4ee00-5da6-11eb-8e46-f950220254c4.png)

**Comment by MattDahEpic** [comment]
Version 16.1.4 should fix this, please reopen if it doesn't!

**Comment by JpegIsMe** [comment]
Works perfectly! Thank you!
