### ISSUE TITLE
allow /odc add to specify tag

### ISSUE THREAD

**Issue by nayfaan** [MattDahEpic/AutoOreDictConvert1.8#22]
See #13 comment at the bottom

With mods that adds metal dusts, gears, etc, the mod adds all the tags on the held item to the list. I have a few suggestions:

ignore more common base tags (e.g. forge:dusts, forge:gears, forge:coins, forge:plates, etc.)
Allow the "/odc add" command to pass arguments of a certain tag like "/odc add forge:dusts/iron"
i.e.
-if no argument is passed, adds all tags to conversion
-if an argument is passed, only add the specified tag to conversion

**Comment by MattDahEpic** [comment]
All set, thanks for the suggestion!

I added it as a new command: `/odc set <tag>`. It'll be in the next version (16.1.8), but that won't be out for a few days. I'm waiting to fix #21 before I make another release.

**Comment by nayfaan** [comment]
can you make a similar command for removing tags too? e.g. /odc unset

**Comment by MattDahEpic** [comment]
The `/odc remove <tag>` command already does that, just don't hold anything when running it.
