### ISSUE TITLE
Mod converting tin to nickel, nickel to tin

### ISSUE THREAD

**Issue by BonaireDreams** [MattDahEpic/AutoOreDictConvert1.8#26]
Forge 40.1.20
Auto Ore Dict 1.18.2-14.0.1
Thermal Exp 1.18.2-1.6.0.8
Thermal Found 1.18.2-1.6.0.20
Immersive Engineering 1.18.2-8.0.1-147

I wanted all ingots to convert to Thermal. I used /odc add while holding Thermal tin. All the Immersive tin AND nickel in my inventory converted to Thermal tin. The same happened when trying to set Thermal nickel as the default. The tin converted to nickel. The Immersive Engineering Silver I had in my hand did not get converted. I have not tried with other ingots to see if this happens with others as well.

![image](https://user-images.githubusercontent.com/5133282/169414794-7da78da0-a6c7-4687-8ac4-3a11a3ab65f7.png)

**Comment by MattDahEpic** [comment]
This is likely because of the `ae2:metal_ingots` tag. If you run `/odc remove ae2:metal_ingots` does the issue resolve? If so, I'll add it to the default ignored tags list so it won't happen in the future.

**Comment by BonaireDreams** [comment]
I thought of that.when I pasted the screenshot and looked at it more closely. Already had game shut down and had to run out. Will test that tonight when I get home and report results.

**Comment by BonaireDreams** [comment]
That worked. Removing the ae2:metal_ingots no longer converts all ingots to the same one.

**Comment by BonaireDreams** [comment]
Found another generic tag that was converting my gold nuggets to Nickel nuggets when I went to set nickel nuggets to Thermal.
forge:nuggets
![image](https://user-images.githubusercontent.com/5133282/169712144-49b7e21d-f386-4aa3-8315-36309f41375d.png)
Both lines were added when I did "/odc add " while holding a thermal nickel nugget
Once I removed the forge:nuggets only nickel nuggets convert.

**Comment by MattDahEpic** [comment]
I've made a release that adds both the `forge:nuggets` and `ae2:metal_ingots` tags to the list to be ignored by default. IT is version 18.0.2 and should be available on CurseForge and Modrinth shortly. Thank you for reporting!

**Comment by BonaireDreams** [comment]
Thanks for the quick fix! Much appreciated!
