### ISSUE TITLE
CRASH: Game crashes when active item slot empties

### ISSUE THREAD

**Issue by JaSpr** [MattDahEpic/AutoOreDictConvert1.8#4]
Just started using the mod, and whenever my current, active item slot empties (e.g. plant the last sapling in the stack, drop the last item in the stack), the entire game crashes.

The modpack is running the latest (1.11-1.0.1) version. 

Crash report: https://gist.github.com/JaSpr/e002ba17c0a1f3d5abaad8af86fa1f94

modpack home: https://minecraft.curseforge.com/projects/forever-modded?gameCategorySlug=modpacks&projectID=254684

**Comment by MattDahEpic** [comment]
A note for the future, pull requests need to be made on the repo you forked from, not the fork. Thanks for the attempt though.
