### ISSUE TITLE
Break Forestry machine recipes

### ISSUE THREAD

**Issue by leagris** [MattDahEpic/AutoOreDictConvert1.8#5]
See: https://github.com/ForestryMC/ForestryMC/issues/1592

**Comment by MattDahEpic** [comment]
Please provide your client's configuration details (mod versions, AODC conversions config, etc).

**Comment by leagris** [comment]
[Modlist.md](https://gist.github.com/leagris/dc82ac7a1a985f7b72c9a0fa941c7c67)
[autooredictconv.cfg](https://gist.github.com/leagris/59f65793d753f46c11bb9d1c44856509#file-autooredictconv-cfg)
[conversions-cfg](https://gist.github.com/leagris/59f65793d753f46c11bb9d1c44856509#file-conversions-cfg)
[mdecore-cfg](https://gist.github.com/leagris/59f65793d753f46c11bb9d1c44856509#file-mdecore-cfg)

**Comment by MattDahEpic** [comment]
A cursory investigation prompts that AODC shouldn't be at fault. I don't touch any recipes or change any internal things related to items. I keep a list of what oredict names are assigned to what items and run a check for anything with that name in your inventory and switch them. 

I'll keep this open for now, let me know what you find or if it indeed is AODC at fault.

**Comment by leagris** [comment]
I have disabled keypress triggered conversion, so AODC process items on-the-fly.
I think it break because it tries to do an oredictionary conversion/substitution from the ghost item slots into the Forestry Carpenter that are used by the Carpenter to record the recipe to process.
Here is how Forestry registers recipes with oredict Ingredients https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/core/PluginCore.java#L304-L309
Then each oredict ingredient is used to build a collection of itemstacks allowed for input: https://github.com/ForestryMC/ForestryMC/blob/0b491f26fc068fb3ede6953717108c9221bd38e5/src/main/java/forestry/factory/recipes/jei/carpenter/CarpenterRecipeWrapper.java#L33-L54

For me, it looks quite straightforward, that, if AODC make substitution on the Carpenter recipe grid while Forestry builds its ingredients collections or if it modify it afterward it can cause such undesirable interaction.

I think what you could try to do is check for the slot type or find a mean to skip conversion on ghost item slots.

**Comment by MattDahEpic** [comment]
[I only convert on the items in the player's inventory.](https://github.com/MattDahEpic/AutoOreDictConvert/blob/1.11.X/src/main/java/com/mattdahepic/autooredictconv/convert/Conversions.java#L34) If forestry's tile contents are being retrieved by the call for the player's inventory, that is not my fault I'm afraid.

**Comment by leagris** [comment]
I hope @mezz or someone from the Forestry Maintainers, can help here find how to to make AODC and Forestry compatible. https://github.com/ForestryMC/ForestryMC/issues/1592#issuecomment-279102808
