### ISSUE TITLE
[Developer's Magic 1.12.2] Ore evaporates in the inventory! magic?

### ISSUE THREAD

**Issue by gamaleev0071** [MattDahEpic/AutoOreDictConvert1.8#6]
after entering the command / odc add
with copper ore from IndustrialCraft2
when trying to put copper ore ANY other than IC2, it simply evaporates from the LOL inventory

Here is a complete log with all the list of everything that happened from the start of the run to the evaporation of the ore
https://paste.ee/p/lDFXn

that for forgive (garbage) from 1.12.2 in the last 12 hours, I have already written 4 times on different Git branches about errors in mods ...

Forgive me for my English, the translator helps me in Google, in Russia even though they learn English but basically the bias in our school was in German and French

**Comment by MattDahEpic** [comment]
When you `/odc add` an IC2 ore as the default ore, any other ore of the same type gets *converted* to IC2 ore. This is the intended behavior.

Please reopen if the ore actually disappears and is not turned into IC2 ore

**Comment by gamaleev0071** [comment]
very, very strange, in order for everything to work it is necessary to re-enter the game as I put it, otherwise the ore you will refill immediately after the addition turns into nothing : \

**Comment by gamaleev0071** [comment]
I found a way out, but you could not do automatic / odc reload after every addition!

**Comment by Mirsario** [comment]
https://github.com/MattDahEpic/AutoOreDictConvert/issues/7
Accidental duplicate on my side, but I did a full explanation + video of the issue there.
