### ISSUE TITLE
Recently registered items disappear, unless "/odc reload" is executed

### ISSUE THREAD

**Issue by Mirsario** [MattDahEpic/AutoOreDictConvert1.8#7]
(You probably just closed a very similar issue, lucky timing)

Basically, what the title says.
**Watch this video, as it demonstrates about everything:**
https://streamable.com/x4d4i

Reproduction steps:
1. Clear the mod's config file.
2. Do "/odc reload".
3. Register some conversions with "/odc add".
4. The registered items may start disappearing from inventory when moved around or added to the inventory.
5. If "/odc reload" is executed, the items will stop disappearing and everything will be fine.
6. Restarting the game after doing this doesn't cause any issues, so I'm fine for now. 👍 

I'm on Windows 10;
Minecraft version is 1.12.2;
Forge version seems to be 14.23.4.2749;
Mod list: https://pastebin.com/uuW3J9R5

**Comment by gamaleev0071** [comment]
lol 
I already suggested to the author to make auto-relog the mod after each addition of the element
