### ISSUE TITLE
Auto Converter is missing textures in hand and inventory

### ISSUE THREAD

**Issue by Brycey92** [MattDahEpic/AutoOreDictConvert1.8#8]
The Auto Converter is missing textures in both the hand and the inventory, but it shows up fine when placed as a block. I don't know whether the issue is with blockstates, models, or something else.

**Comment by Breadabix** [comment]
I see this is closed but im on the latest mod version for 1.12 and the block is missing its texture in my hand/inventory. I am not on galaxy-craft and whatever I do with texturepacks changing the item model file I cant make it work. Is there a fix for this that im missing or is it something ill have to live with?
